version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: ssh -o StrictHostKeyChecking=no ubuntu@ec2-34-212-27-73.us-west-2.compute.amazonaws.com "bash -s" < deploy.sh

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
